# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:
let
  inherit (haskellPackages) cabal postgresqlSimple
  ;
in cabal.mkDerivation (self: {
  pname = "postgresql-simple-examples";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = with haskellPackages; [
    mtl transformers postgresqlSimple
  ];
  buildTools = with haskellPackages; [ cabalInstall ];
})
